[Service]
Environment=AIBA_HOME_URL=https://xiaoaijia.cn/
Environment="CORS_ORIGINS=https://xiaoaijia.cn,https://xiaoaijia.cn:5207,https://xiaoaijia.cn:5214,https://xiaoaijia.cn:5216,https://xiaoaijia.cn:5217,https://www.xiaoaijia.cn,https://www.xiaoaijia.cn:5207,https://www.xiaoaijia.cn:5214,https://www.xiaoaijia.cn:5216,https://www.xiaoaijia.cn:5217"
